### ISSUE TITLE
Allow "Restore as a new course"

### ISSUE THREAD

**Issue by ctchanandy** [sagarrr/json-mbz#1]
Now the created mbz can only be "restore into an existing course" which require user to created an empty course first. If it is used to "restore as a new course", there will be error.
![screencapture-127-0-0-1-moodle-backup-restore-php-2018-07-09-14_01_32](https://user-images.githubusercontent.com/2976175/42433168-ac031458-8380-11e8-9305-374eeb51a7bd.png)

**Comment by sagarrr** [comment]
Noted and Fixed!
